# Generated by Django 5.0.6 on 2025-01-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_remove_complaint_assigned_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='contactNo',
            new_name='contact_no',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='complaintGroup',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='preferredTime',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='status',
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_group',
            field=models.CharField(choices=[('Common', 'Common'), ('Room', 'Room')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='bhavan',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='requirement',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='room',
            field=models.CharField(max_length=255),
        ),
    ]
