# Generated by Django 5.0.6 on 2025-01-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_rename_contactno_complaint_contact_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='bitsId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
