# Generated by Django 5.0.6 on 2025-01-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_bitsid_complaint_description_complaint_ist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
