# Generated by Django 5.0.6 on 2025-01-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaint_preferred_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='bitsId',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='description',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='ist',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='name',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='time',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=100),
        ),
    ]
